version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: stocksense_postgres
    restart: always
    environment:
      POSTGRES_DB: stocksense
      POSTGRES_USER: stocksense
      POSTGRES_PASSWORD: stocksense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
